---
- name: deploy incus instances by inventory on localhost
  hosts: localhost
  gather_facts: no
  vars_files:
    - group_vars/redis/vault.yml

  tasks:
    - name: Create Cloud-Init files for each redis host
      template:
        src: templates/cloud-init.yaml.j2
        dest: "/tmp/{{ item }}.cloud-init.yaml"
      loop: "{{ groups['redis'] }}"
      vars:
         vm_ip: "{{ hostvars[item].ansible_host }}"
      tags:
        - ssh
    - name: Lets have a look
      debug:
        msg: "Vault Data: {{ vault_ssh_pubkey }}"
      tags:
        - debug

    - name: Generate network-config cloud-init
      template:
        src: templates/cloud-net.yaml.j2
        dest: "/tmp/{{ item }}-network.yaml"
      loop: "{{ groups['redis'] }}"
      vars:
        vm_ip: "{{ hostvars[item].ansible_host }}"
        vm_name: "{{ item }}"
      tags:
        - net

    - name: Run incus with these files
      ansible.builtin.shell: |
        incus launch images:debian/13/cloud {{ item }} --config=user.user-data="$(cat /tmp/{{ item }}.cloud-init.yaml)" --config=user.network-config="$(cat /tmp/{{ item }}-network.yaml)"
      loop: "{{ groups['redis'] }}"
      tags:
        - deploy

