---
- name: Check if incus instance exists
  delegate_to: localhost
  ansible.builtin.command: incus list --format=json
  register: incus_list
  changed_when: false
  run_once: true
- name: Parse template into lookup
  delegate_to: localhost
  vars:
    cloud_init_template_map:
      "debian/12/cloud": "templates/cloud-init-deb12.yaml.j2"
      "debian/13/cloud": "templates/cloud-init-deb13.yaml.j2"
    existing: "{{ incus_list.stdout | from_json | map(attribute='name') }}"
    vm_ip: "{{ ansible_host }}"
    login_config: "{{ lookup('template', cloud_init_template_map[incus_image_designator], vm_ip=vm_ip) }}"
    network_config: "{{ lookup('template', 'templates/cloud-net.yaml.j2', vm_ip=vm_ip) }}"
  ansible.builtin.command: >
    incus launch images:{{ incus_image_designator }} {{ inventory_hostname }}
      --config=user.user-data={{ login_config | quote }}
      --config=user.network-config={{ network_config | quote }}
      -c limits.cpu={{ incus_image_cpu | default('2') }}
      -c limits.memory={{ incus_image_mem | default('4GiB') }}
      --device root,size={{ incus_image_root | default('8GiB') }}

  when: inventory_hostname not in existing
  changed_when: true
